Fixed `PCL_WARNINGS_ARE_ERRORS` option and some compile warnings (#4695)
* fixed PCL_WARNINGS_ARE_ERRORS option in CMakeLists

* fixed -Werror=class-memaccess in pcl/common/include/pcl/common/impl/io.hpp

fixed compile error like this,  when using -Werror:
pcl/common/include/pcl/common/impl/io.hpp:139:12: error: 'void* memcpy(void*, const void*, size_t)' copying an object of non-trivial type 'struct pcl::PointNormal' from an array of 'const struct pcl::PointXYZ' [-Werror=class-memaccess]

* fixed some memset on non-POD types

* fixed new errors

* restored 3rd opennurbs modification

* added compile flags for 3rd party & fixed deprecated copy

* fixed errors & set copy functions to default

* Update surface/include/pcl/surface/impl/convex_hull.hpp

fixed redundancy code with already defined data type

Co-authored-by: Kunal Tyagi <tyagi.kunal@live.com>

* fixed hull size in convex_hull.hpp

* added type AlignedVector for pcl/types.h

* fixed include library of Eigen::aligned_allocator

* fixed noexcept-type errors & added exclusive rules in CMakeLists

* resolved conflicts with master

* added inline comments

* added rules and fixed codes for compile on GPU

* made unsigned declaration more explict

* fixed noexcept-type error in test_common.cpp

* Moved for-loop into empty templated function

* Moved copyPointCloudMemcpy into detail namespace

Co-authored-by: Kunal Tyagi <tyagi.kunal@live.com>