Fix error C3016 on MSVC with OpenMP
MSVC doesn't support an OpenMP versions earlier higher than 2.0.
The index variable in an OpenMP 2.0 for statement must be a signed integral type.